version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'discord.js'
        versions: ['13.x']
      - dependency-name: 'framer-motion'
        versions: ['2.x', '3.x', '4.x', '5.x', '6.x']
      - dependency-name: 'node-fetch'
        versions: ['3.x']
