version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: 'cypress'
        versions: ['7.x']
      - dependency-name: '@cypress/react'
        versions: ['5.x']
      - dependency-name: 'framer-motion'
        versions: ['2.x', '3.x', '4.x']
