name: CMS
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Sanity
        run: npx @sanity/cli@3.20.0 install
        working-directory: cms

      - name: Deploy live studio
        run: npx @sanity/cli@3.20.0 deploy
        working-directory: cms
        env:
          SANITY_STUDIO_API_PROJECT_ID: 5hlpazgd
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN_PRODUCTION }}
          SANITY_STUDIO_PREVIEW_TOKEN: ${{ secrets.SANITY_STUDIO_PREVIEW_TOKEN }}
          SANITY_STUDIO_ENVIRONMENT: production
