name: End-to-end tests (PR)

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.16.0-chrome89-ff86
    strategy:
      # Make sure not to cancel other containers when one test fails, as this
      # will kill Cypress processes leaving the Dashboard hanging.
      # See: https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - name: Run unit tests
        run: npm test

      - name: Deploy preview
        run: 'npx vercel --token ${VERCEL_TOKEN} > preview-url.txt'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Expose deploy URL
        run: |
          export PREVIEW_URL=$(cat preview-url.txt)
          echo "PREVIEW_URL=${PREVIEW_URL}" >> $GITHUB_ENV

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          record: true
          parallel: true
          group: 'Integration tests'
        env:
          CYPRESS_BASE_URL: ${{ env.PREVIEW_URL }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          COMMIT_INFO_BRANCH: ${{ github.head_ref }}
          COMMIT_INFO_SHA: ${{ github.sha }}
